{"name": "Ошибка авторизации для несуществующего логина или пароля", "status": "passed", "description": "Проверяем, что API возвращает 404 при попытке авторизации с неверными данными", "steps": [{"name": "Попытка авторизации с login=valid_login, password=wrong_password", "status": "passed", "start": 1755418657432, "stop": 1755418657743}], "parameters": [{"name": "login", "value": "'valid_login'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1755418657432, "stop": 1755418657744, "uuid": "37dacbb8-3c83-4aea-8585-30b3c714ea4e", "historyId": "fe5cc95d9c79f18d8b1ba850d2c8bfa8", "testCaseId": "a7b4c63b76cfd5451f09db3c2f42c8f4", "fullName": "tests.test_login_courier.TestCourierLogin#test_authorization_fails_invalid_or_nonexistent_user", "labels": [{"name": "feature", "value": "Авторизация курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-Q5OERPF"}, {"name": "thread", "value": "8268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}], "titlePath": ["tests", "test_login_courier.py", "TestCourierLogin"]}