{"name": "Ошибка авторизации для несуществующего логина или пароля", "status": "passed", "description": "Проверяем, что API возвращает 404 при попытке авторизации с неверными данными", "steps": [{"name": "Попытка авторизации с login=wrong_login, password=12345", "status": "passed", "start": 1755419657009, "stop": 1755419657285}], "parameters": [{"name": "login", "value": "'wrong_login'"}, {"name": "password", "value": "'12345'"}], "start": 1755419657008, "stop": 1755419657285, "uuid": "00b00695-dee7-477e-b5ef-f80c64b69c69", "historyId": "e8da1239f885727e1ccebb7f89d21da4", "testCaseId": "a7b4c63b76cfd5451f09db3c2f42c8f4", "fullName": "tests.test_login_courier.TestCourierLogin#test_authorization_fails_invalid_or_nonexistent_user", "labels": [{"name": "feature", "value": "Авторизация курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-Q5OERPF"}, {"name": "thread", "value": "15844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}], "titlePath": ["tests", "test_login_courier.py", "TestCourierLogin"]}