{"name": "Ошибка авторизации для несуществующего логина или пароля", "status": "passed", "description": "Проверяем, что API возвращает 404 при попытке авторизации с неверными данными", "steps": [{"name": "Попытка авторизации с login=wrong_login, password=12345", "status": "passed", "start": 1755418215819, "stop": 1755418216153}], "parameters": [{"name": "login", "value": "'wrong_login'"}, {"name": "password", "value": "'12345'"}], "start": 1755418215819, "stop": 1755418216153, "uuid": "dc7ccf50-b914-41fd-9bc7-cfbeeb619eb1", "historyId": "e8da1239f885727e1ccebb7f89d21da4", "testCaseId": "a7b4c63b76cfd5451f09db3c2f42c8f4", "fullName": "tests.test_login_courier.TestCourierLogin#test_authorization_fails_invalid_or_nonexistent_user", "labels": [{"name": "feature", "value": "Авторизация курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-Q5OERPF"}, {"name": "thread", "value": "16624-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}], "titlePath": ["tests", "test_login_courier.py", "TestCourierLogin"]}